import type { Metadata } from "next";
import React, { Suspense } from "react";
import { Inter, Roboto } from "next/font/google";
// import localFont from "next/font/local";
import AuthProvider from "./auth/provider";
import "./globals.css";
import NavBar from "./NavBar";

const inter = Inter({ subsets: ["latin"] });

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });

// const poppins = localFont({
//   src: "/fonts/poppins.woff2",
//   variable: "--font-poppins",
// });

export const metadata: Metadata = {
  // used for SEO
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    // used for SEO when shared on social media
    title: "Create Next App",
    description: "Generated by create next app",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <html lang="en" data-theme="synthwave"> */}
      <AuthProvider>
        <body className={inter.className}>
          <NavBar />
          <main className="p-5">{children}</main>
        </body>
      </AuthProvider>
    </html>
  );
}
